name: Notion Sync Bot

on:
  push:
    branches: [ "main" ]

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir notion-client PyGithub

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_STATUS_DB_ID: ${{ secrets.NOTION_STATUS_DB_ID }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: python intergrate
